"""
Agent 5: Documentation Agent
Generates concise, professional documentation for the modernized code.
Optimized for speed: trimmed prompt, capped inputs, fast model.
"""

import os
from utils.llm_client import call_llm
from utils.logger import get_logger

logger = get_logger("DocumentationAgent")

# Use the fastest available Groq model for documentation
FAST_MODEL = os.getenv("GROQ_DOC_MODEL", "llama-3.1-8b-instant")

# Max characters fed into the prompt to avoid token overload
_MAX_CODE_CHARS       = 3000
_MAX_PSEUDOCODE_CHARS = 2000

# How-to-run instructions per target language
_HOW_TO_RUN = {
    "python": """\
## How to Run

1. Make sure Python 3.8+ is installed — verify with `python --version`
2. (Optional) Create a virtual environment: `python -m venv venv && source venv/bin/activate`
3. Install any dependencies listed at the top of the file: `pip install -r requirements.txt`
4. Run the program: `python {filename}.py`
""",
    "java": """\
## How to Run

1. Make sure JDK 17+ is installed — verify with `java -version`
2. Compile the source file: `javac {filename}.java`
3. Run the compiled class: `java {filename}`
4. If the project uses Maven/Gradle, run `mvn compile exec:java` or `gradle run` instead.
""",
    "c": """\
## How to Run

1. Make sure GCC is installed — verify with `gcc --version`
2. Compile the source file: `gcc -o {filename} {filename}.c`
3. Run the binary:
   - Linux/macOS: `./{filename}`
   - Windows: `{filename}.exe`
4. For debug builds add the `-g` flag: `gcc -g -o {filename} {filename}.c`
""",
    "cpp": """\
## How to Run

1. Make sure G++ is installed — verify with `g++ --version`
2. Compile the source file: `g++ -std=c++17 -o {filename} {filename}.cpp`
3. Run the binary:
   - Linux/macOS: `./{filename}`
   - Windows: `{filename}.exe`
4. For debug builds add the `-g` flag: `g++ -g -std=c++17 -o {filename} {filename}.cpp`
""",
}

DOCUMENTATION_PROMPT = """You are a technical writer. The original {source_language} code has been modernized to {target_language} by an AI pipeline.

PROJECT: {project_title}

--- FINAL {target_language_upper} CODE (excerpt) ---
{translated_code}

--- PSEUDOCODE SUMMARY (excerpt) ---
{pseudocode}

Write clean Markdown documentation with ONLY these sections. Be concise — each section should be 3-6 lines max.

# {project_title} — Documentation

## Overview
What this program does and who would use it.

## Function Reference
List each function: name, purpose, parameters, return value.

## Key Business Logic
Important rules, formulas, and conditions from the original code.

## Modernization Notes
What changed from {source_language} to {target_language}.

---
*Generated by NewGenCode 5-Agent Pipeline*
"""


def _trim(text: str, max_chars: int) -> str:
    """Trim text to max_chars, appending a note if truncated."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + f"\n... [trimmed for brevity]"


class DocumentationAgent:
    """
    Generates concise technical documentation for the modernized codebase.
    This is the fifth and final agent in the NewGenCode pipeline.
    """

    def __init__(self):
        logger.info("DocumentationAgent initialized")

    def document(
        self,
        pseudocode: str,
        translated_code: str,
        review_report: str,
        source_language: str = "COBOL",
        target_language: str = "python",
        filename: str = "program"
    ) -> str:
        """
        Generate documentation for the modernized codebase.

        Args:
            pseudocode:       IR pseudocode from IRGeneratorAgent
            translated_code:  Final debugged code from DebuggerAgent
            review_report:    Debug review report (not used in prompt to save tokens)
            source_language:  Original legacy language
            target_language:  The modern target language
            filename:         Original filename (used as project title)

        Returns:
            Markdown documentation string (includes How to Run section)
        """
        logger.info(f"Generating documentation for {filename}...")

        project_title = filename.replace("_", " ").replace("-", " ").title()
        # Normalise filename for code snippets (strip extension if present)
        base_filename = os.path.splitext(filename)[0]

        prompt = DOCUMENTATION_PROMPT.format(
            source_language=source_language.upper(),
            target_language=target_language.capitalize(),
            target_language_upper=target_language.upper(),
            project_title=project_title,
            translated_code=_trim(translated_code, _MAX_CODE_CHARS),
            pseudocode=_trim(pseudocode, _MAX_PSEUDOCODE_CHARS),
        )

        logger.info(f"Sending to {FAST_MODEL} for documentation...")
        documentation = call_llm(prompt, temperature=0.3, model=FAST_MODEL)

        # Append the "How to Run" section with the real filename injected
        lang_key = target_language.lower()
        how_to_run = _HOW_TO_RUN.get(lang_key, "")
        if how_to_run:
            how_to_run = how_to_run.format(filename=base_filename)
            # Insert before the final divider line if present, else append
            if "\n---\n" in documentation:
                documentation = documentation.replace(
                    "\n---\n",
                    f"\n{how_to_run}\n---\n",
                    1,
                )
            else:
                documentation += f"\n{how_to_run}"

        logger.info(f"Documentation complete. Output: {len(documentation)} characters")
        return documentation